defmodule SillySeahorse.Noun do
  @moduledoc false
  @nouns {
    "aardvark",
    "aardwolf",
    "abyssinian",
    "addax",
    "afghan hound",
    "agama lizard",
    "agouti",
    "aidi",
    "ainu",
    "airedoodle",
    "akbash",
    "akita",
    "alabai",
    "albatross",
    "albino",
    "alligator",
    "allosaurus",
    "alpaca",
    "alpine goat",
    "alusky",
    "amano shrimp",
    "amargasaurus",
    "amberjack",
    "american eel",
    "amur leopard",
    "anaconda",
    "anchovies",
    "angelfish",
    "angelshark",
    "anglerfish",
    "angora goat",
    "anhinga",
    "anole lizard",
    "anomalocaris",
    "ant",
    "anteater",
    "antelope",
    "anteosaurus",
    "aoudad sheep",
    "apatosaurus",
    "ape",
    "apple moth",
    "arabian wolf",
    "arapaima",
    "archerfish",
    "arctic char",
    "arctic fox",
    "arctic hare",
    "arctic wolf",
    "arctodus",
    "arctotherium",
    "armadillo",
    "armyworm",
    "arthropleura",
    "asian carp",
    "asp",
    "assassin bug",
    "atlantic cod",
    "atlas beetle",
    "atlas moth",
    "aurochs",
    "aussiedoodle",
    "aussiedor",
    "aussiepom",
    "avocet",
    "axolotl",
    "ayam cemani",
    "aye-aye",
    "azawakh",
    "babirusa",
    "baboon",
    "badger",
    "bagworm moth",
    "baiji",
    "bald eagle",
    "baleen whale",
    "balinese",
    "balkan lynx",
    "ball python",
    "bamboo rat",
    "bamboo shark",
    "bamboo worms",
    "banana eel",
    "banded krait",
    "bandicoot",
    "barb",
    "barbet",
    "barinasuchus",
    "bark beetle",
    "barn owl",
    "barn spider",
    "barn swallow",
    "barnacle",
    "barnevelder",
    "barosaurus",
    "barracuda",
    "barred owl",
    "barylambda",
    "basenji dog",
    "basilosaurus",
    "bass",
    "bassador",
    "basset hound",
    "bassetoodle",
    "bat",
    "batfish",
    "baya",
    "bea-tzu",
    "beabull",
    "beagador",
    "beagle",
    "beaglier",
    "beago",
    "bear",
    "beaski",
    "beauceron",
    "beaver",
    "bed bugs",
    "bee",
    "bee-eater",
    "beefalo",
    "beetle",
    "beewolf wasp",
    "beluga whale",
    "bengal tiger",
    "bergamasco",
    "bernedoodle",
    "betta fish",
    "bhutan takin",
    "bichir",
    "bichon frise",
    "bichpoo",
    "bilby",
    "binturong",
    "bird",
    "bird snake",
    "birman",
    "bison",
    "black aphids",
    "black bass",
    "black mamba",
    "black marlin",
    "black wasp",
    "blind snake",
    "blobfish",
    "blood python",
    "bloodhound",
    "blowfly",
    "blue catfish",
    "blue iguana",
    "blue jay",
    "blue racer",
    "blue shark",
    "blue tanager",
    "blue tang",
    "blue whale",
    "bluebird",
    "bluefin tuna",
    "bluefish",
    "bluegill",
    "boas",
    "bobcat",
    "bobolink",
    "boer goat",
    "boerboel",
    "boggle",
    "boiga",
    "bombay",
    "bonefish",
    "bongo",
    "bonito fish",
    "bonobo",
    "boomslang",
    "borador",
    "bordoodle",
    "borkie",
    "boskimo",
    "bowfin",
    "box turtle",
    "boxachi",
    "boxador",
    "boxer dog",
    "boxerdoodle",
    "boxfish",
    "boxsky",
    "boxweiler",
    "briard",
    "brittany",
    "brontosaurus",
    "brook trout",
    "brown bear",
    "brown hyena",
    "brown snake",
    "brug",
    "budgerigar",
    "buffalo",
    "buffalo fish",
    "bull shark",
    "bull terrier",
    "bull trout",
    "bullboxer",
    "bulldog",
    "bullfrog",
    "bullmastiff",
    "bullsnake",
    "bumblebee",
    "burmese",
    "bush baby",
    "bush dog",
    "bush viper",
    "bushbaby",
    "butterfly",
    "cabbage moth",
    "cactus moth",
    "cactus mouse",
    "cactus wren",
    "caecilian",
    "caiman",
    "camel",
    "camel spider",
    "canaan dog",
    "canada lynx",
    "canary",
    "cane corso",
    "cane rat",
    "cane spider",
    "cantil",
    "canvasback",
    "cape lion",
    "capuchin",
    "capybara",
    "caracal",
    "cardinal",
    "caribou",
    "carolina dog",
    "carp",
    "carpet viper",
    "cascabel",
    "cassowary",
    "cat",
    "cat snake",
    "caterpillar",
    "catfish",
    "cava tzu",
    "cavador",
    "cavapoo",
    "cave bear",
    "cave lion",
    "centipede",
    "cephalaspis",
    "ceratopsian",
    "ceratosaurus",
    "cesky fousek",
    "chameleon",
    "chamois",
    "chartreux",
    "cheagle",
    "cheetah",
    "chi chi",
    "chickadee",
    "chicken",
    "chigger",
    "chihuahua",
    "chilesaurus",
    "chimaera",
    "chimpanzee",
    "chinchilla",
    "chinook",
    "chipit",
    "chipmunk",
    "chipoo",
    "chiton",
    "chiweenie",
    "chorkie",
    "chow chow",
    "chow pom",
    "chusky",
    "cicada",
    "cichlid",
    "clam",
    "click beetle",
    "clock spider",
    "clothes moth",
    "clownfish",
    "coati",
    "cobia fish",
    "cobra",
    "cobras",
    "cockalier",
    "cockapoo",
    "cockatiel",
    "cockatoo",
    "cockle",
    "cockroach",
    "coconut crab",
    "codfish",
    "codling moth",
    "coelacanth",
    "collie",
    "comet moth",
    "common carp",
    "common frog",
    "common loon",
    "common raven",
    "common toad",
    "cone snail",
    "conger eel",
    "congo snake",
    "conure",
    "copperhead",
    "coral",
    "coral snake",
    "corella",
    "corgidor",
    "corgipoo",
    "corkie",
    "cormorant",
    "corn earworm",
    "corn rex cat",
    "corn snake",
    "cory catfish",
    "coryphodon",
    "cottonmouth",
    "coues deer",
    "cougar",
    "cow",
    "coyote",
    "crab",
    "crab spider",
    "crane",
    "crappie fish",
    "crayfish",
    "cricket",
    "crocodile",
    "cross fox",
    "crow",
    "crucian carp",
    "cuban boa",
    "cuckoo",
    "cuscus",
    "cuttlefish",
    "dachsador",
    "dachshund",
    "daeodon",
    "dalmadoodle",
    "dalmador",
    "dalmatian",
    "damselfish",
    "daniff",
    "danios",
    "daug",
    "death adder",
    "deer",
    "deer mouse",
    "deer tick",
    "deinocheirus",
    "deinosuchus",
    "desert wolf",
    "desmostylus",
    "devon rex",
    "dhole",
    "dik-dik",
    "dimetrodon",
    "dingo",
    "dinocrocuta",
    "dinofelis",
    "dinopithecus",
    "dinosaurs",
    "diplodocus",
    "diprotodon",
    "dire wolf",
    "disco clam",
    "discus",
    "discus fish",
    "diving duck",
    "dobsonfly",
    "dodo",
    "dodo bird",
    "doedicurus",
    "dog",
    "dog tick",
    "dolphin",
    "donkey",
    "dorgi",
    "dorkie",
    "dormouse",
    "douc",
    "dove",
    "doxiepoo",
    "doxle",
    "dragon eel",
    "dragon snake",
    "dragonfish",
    "dragonfly",
    "drever",
    "drum fish",
    "duck",
    "dugong",
    "dung beetle",
    "dunker",
    "dunkleosteus",
    "dunnock",
    "dusky shark",
    "dutch rabbit",
    "dwarf boa",
    "eagle",
    "eagle ray",
    "eared grebe",
    "earthworm",
    "earwig",
    "echidna",
    "edible frog",
    "eel",
    "eel catfish",
    "eelpout",
    "egret",
    "egyptian mau",
    "eider",
    "eland",
    "elasmosaurus",
    "electric eel",
    "elegant tern",
    "elephant",
    "elf owl",
    "elk",
    "ember tetra",
    "emu",
    "ermine",
    "eryops",
    "escolar",
    "eskimo dog",
    "eskipoo",
    "eurasian jay",
    "eurasier",
    "eurypterus",
    "evening bat",
    "fairy-wren",
    "falcon",
    "fallow deer",
    "false cobra",
    "fancy mouse",
    "fangtooth",
    "feather star",
    "feist",
    "fennec fox",
    "ferret",
    "fiddler crab",
    "fierce snake",
    "fin whale",
    "finch",
    "fire eel",
    "firefly",
    "fish",
    "fisher",
    "fishing cat",
    "flamingo",
    "flea",
    "flea beetle",
    "florida gar",
    "flounder",
    "flour beetle",
    "fluke fish",
    "fly",
    "flycatcher",
    "flying fish",
    "flying lemur",
    "flying snake",
    "forest cobra",
    "fossa",
    "fox",
    "fox snakes",
    "fox squirrel",
    "fox terrier",
    "french lop",
    "frenchton",
    "frengle",
    "frigatebird",
    "frog",
    "frogfish",
    "frug",
    "fruit bat",
    "fruit fly",
    "fugu fish",
    "fur seal",
    "furrow bee",
    "gaboon viper",
    "gadwall",
    "galago",
    "gannet",
    "gar",
    "garden eel",
    "garter snake",
    "gastornis",
    "gaur",
    "gazelle",
    "gecko",
    "gemfish",
    "genet",
    "gerbil",
    "gerenuk",
    "german spitz",
    "gharial",
    "ghost crab",
    "giant beaver",
    "giant clam",
    "giant isopod",
    "giant weta",
    "gibbon",
    "gila monster",
    "giraffe",
    "glass frog",
    "glass lizard",
    "glechon",
    "glow-worm",
    "glowworm",
    "gnat",
    "goat",
    "goberian",
    "goblin shark",
    "goby fish",
    "goldador",
    "goldcrest",
    "golden dox",
    "golden eagle",
    "golden irish",
    "golden mole",
    "golden saint",
    "golden trout",
    "goldendoodle",
    "goldfish",
    "goliath frog",
    "gollie",
    "goose",
    "gopher",
    "gopher snake",
    "goral",
    "gorgosaurus",
    "gorilla",
    "goshawk",
    "gourami",
    "grass carp",
    "grass snake",
    "grass spider",
    "grasshopper",
    "gray catbird",
    "gray fox",
    "gray whale",
    "great dane",
    "great egret",
    "grebe",
    "green anole",
    "green aphids",
    "green frog",
    "green heron",
    "green mamba",
    "green snake",
    "grey heron",
    "grey seal",
    "greyhound",
    "griffonshire",
    "grizzly bear",
    "groenendael",
    "ground snake",
    "groundhog",
    "grouper",
    "grouse",
    "grunion",
    "gudgeon fish",
    "guinea fowl",
    "guinea pig",
    "guineafowl",
    "gulper eel",
    "guppy",
    "gypsy moth",
    "habu snake",
    "haddock",
    "hagfish",
    "hainosaurus",
    "halibut",
    "hallucigenia",
    "hamster",
    "harbor seal",
    "hare",
    "harp seal",
    "harpy eagle",
    "harrier",
    "hartebeest",
    "havamalt",
    "havanese",
    "havapoo",
    "havashire",
    "havashu",
    "hawk",
    "hedgehog",
    "helicoprion",
    "hellbender",
    "hermit crab",
    "heron",
    "herring",
    "herring gull",
    "himalayan",
    "hippopotamus",
    "hoary bat",
    "hobo spider",
    "hogfish",
    "hoki fish",
    "hokkaido",
    "honey badger",
    "honey bee",
    "hooded seal",
    "hoopoe",
    "hoopoe bird",
    "horgi",
    "horn shark",
    "hornbill",
    "horned adder",
    "horned grebe",
    "horned viper",
    "hornet",
    "horse",
    "horsefly",
    "house finch",
    "house wren",
    "housefly",
    "hovasaurus",
    "hovawart",
    "human",
    "hummingbird",
    "huntaway",
    "huskador",
    "huskita",
    "husky",
    "husky jack",
    "huskydoodle",
    "hyaenodon",
    "hyena",
    "hyrax",
    "ibex",
    "ibis",
    "ibis bird",
    "ibizan hound",
    "icadyptes",
    "ichthyostega",
    "iguana",
    "iguanodon",
    "impala",
    "inchworm",
    "indian cobra",
    "indigo snake",
    "indri",
    "insect",
    "insects",
    "io moth",
    "irish doodle",
    "irish elk",
    "irish setter",
    "ivy bee",
    "jabiru",
    "jacana",
    "jack-chi",
    "jackabee",
    "jackal",
    "jackdaw",
    "jackrabbit",
    "jagdterrier",
    "jaguar",
    "jaguarundi",
    "jamaican boa",
    "javanese",
    "jellyfish",
    "jerboa",
    "jewel beetle",
    "john dory",
    "jonah crab",
    "joro spider",
    "junglefowl",
    "kagu",
    "kai ken",
    "kakapo",
    "kangaroo",
    "kangaroo rat",
    "katydid",
    "kea",
    "keagle",
    "keelback",
    "keeshond",
    "kermode bear",
    "kestrel",
    "kestrel bird",
    "keta salmon",
    "key deer",
    "khao manee",
    "kiang",
    "kiko goat",
    "killdeer",
    "killer whale",
    "killifish",
    "kinder goat",
    "king cobra",
    "king crab",
    "king eider",
    "king penguin",
    "king quail",
    "king salmon",
    "king snake",
    "king vulture",
    "kingfisher",
    "kingklip",
    "kinkajou",
    "kishu",
    "kissing bugs",
    "kit fox",
    "kiwi",
    "kiwi bird",
    "klipspringer",
    "knifefish",
    "knight anole",
    "koala",
    "kodiak bear",
    "kodkod",
    "koi fish",
    "komondor",
    "koolie",
    "korean jindo",
    "kori bustard",
    "kouprey",
    "kowari",
    "krait",
    "krill",
    "kudu",
    "kudzu bug",
    "kuvasz",
    "labahoula",
    "labmaraner",
    "labrabull",
    "labradane",
    "labradoodle",
    "labraheeler",
    "labrottie",
    "lace bug",
    "lace monitor",
    "ladybug",
    "ladyfish",
    "lake trout",
    "lamprey",
    "lancetfish",
    "leech",
    "leedsichthys",
    "lemming",
    "lemon shark",
    "lemur",
    "leonberger",
    "leopard",
    "leopard cat",
    "leopard frog",
    "leopard seal",
    "lesser scaup",
    "lhasa apso",
    "lhasapoo",
    "liger",
    "limpet",
    "linnet",
    "lion",
    "lionfish",
    "liopleurodon",
    "livyatan",
    "lizard",
    "lizardfish",
    "llama",
    "loach",
    "lobster",
    "locust",
    "longnose gar",
    "lorikeet",
    "loris",
    "lowchen",
    "lumpfish",
    "luna moth",
    "lungfish",
    "lurcher",
    "lykoi cat",
    "lynx",
    "lyrebird",
    "lystrosaurus",
    "macaque",
    "macaw",
    "machaeroides",
    "macrauchenia",
    "madora moth",
    "maggot",
    "magpie",
    "mahi mahi",
    "maiasaura",
    "maine coon",
    "mako shark",
    "mal shi",
    "malchi",
    "mallard",
    "malteagle",
    "maltese",
    "maltipom",
    "maltipoo",
    "mamba",
    "manatee",
    "mandrill",
    "maned wolf",
    "manta ray",
    "mara",
    "marble fox",
    "margay",
    "marine toad",
    "markhor",
    "marmoset",
    "marmot",
    "marsh frog",
    "mason bee",
    "massasauga",
    "mastador",
    "mastiff",
    "mauzer",
    "may beetle",
    "mayfly",
    "meagle",
    "mealybug",
    "meerkat",
    "megalania",
    "megalochelys",
    "megalodon",
    "meganeura",
    "megatherium",
    "meiolania",
    "merganser",
    "microraptor",
    "miki",
    "milk snake",
    "milkfish",
    "millipede",
    "mini lop",
    "mink",
    "minke whale",
    "mockingbird",
    "mojarra",
    "mola mola",
    "mole",
    "mole crab",
    "mole cricket",
    "mole snake",
    "mollusk",
    "molly",
    "mongoose",
    "mongrel",
    "monkey",
    "monkfish",
    "moonglow boa",
    "moorhen",
    "moorhen bird",
    "moose",
    "moray eel",
    "morkie",
    "mosasaurus",
    "mosquito",
    "moth",
    "mountain cur",
    "mouse",
    "mouse spider",
    "mouse-deer",
    "mud snake",
    "mudi",
    "mudpuppy",
    "mudskipper",
    "mule",
    "mule deer",
    "mulga snake",
    "mullet fish",
    "muntjac",
    "muscovy duck",
    "musk deer",
    "muskellunge",
    "muskox",
    "muskrat",
    "myna bird",
    "nabarlek",
    "naegleria",
    "nalolo fish",
    "narwhal",
    "natterjack",
    "nautilus",
    "neanderthal",
    "nebelung",
    "needlefish",
    "nematode",
    "neon tetra",
    "newfoundland",
    "newfypoo",
    "newt",
    "nguni cattle",
    "night adder",
    "night heron",
    "night snake",
    "nightingale",
    "nightjar",
    "nile monitor",
    "nile perch",
    "nilgai",
    "no see ums",
    "noodlefish",
    "norway rat",
    "nubian goat",
    "nudibranch",
    "numbat",
    "nuralagus",
    "nurse shark",
    "nut weevil",
    "nuthatch",
    "nutria",
    "nyala",
    "oak toad",
    "oarfish",
    "ocean perch",
    "ocean pout",
    "ocelot",
    "octopus",
    "oilfish",
    "okapi",
    "olingo",
    "olive baboon",
    "olive python",
    "olm",
    "onager",
    "opabinia",
    "opah",
    "opaleye",
    "opossum",
    "orangutan",
    "orb weaver",
    "orca",
    "ori-pei",
    "oribi",
    "oriole",
    "ornithomimus",
    "oscar fish",
    "osprey",
    "ostracod",
    "ostrich",
    "otter",
    "otterhound",
    "ovenbird",
    "oviraptor",
    "owl",
    "owlfly",
    "ox",
    "oxpecker",
    "oyster",
    "ozark bass",
    "paddlefish",
    "pademelon",
    "palaeophis",
    "pallas's cat",
    "palm rat",
    "panda",
    "pangolin",
    "panther",
    "papillon",
    "parakeet",
    "parrot",
    "parrot snake",
    "parrotfish",
    "parrotlet",
    "partridge",
    "patagotitan",
    "patas monkey",
    "pea puffer",
    "peagle",
    "peccary",
    "peekapoo",
    "pekingese",
    "pelagornis",
    "pelican",
    "pelycosaurs",
    "penguin",
    "perch fish",
    "persian",
    "pheasant",
    "phorusrhacos",
    "phytosaurs",
    "pied tamarin",
    "pig",
    "pigeon",
    "pika",
    "pike fish",
    "pilot whale",
    "pine beetle",
    "pine marten",
    "pine siskin",
    "pine snake",
    "pinfish",
    "pink salmon",
    "pipe snake",
    "pipefish",
    "piranha",
    "pit bull",
    "pit viper",
    "pitador",
    "pitsky",
    "platybelodon",
    "platypus",
    "plesiosaur",
    "pliosaur",
    "plott hounds",
    "pointer",
    "polacanthus",
    "polar bear",
    "polecat",
    "pollock fish",
    "pomapoo",
    "pomchi",
    "pomeagle",
    "pomeranian",
    "pompano fish",
    "pomsky",
    "pond skater",
    "poochon",
    "poodle",
    "poogle",
    "pool frog",
    "porcupine",
    "porpoise",
    "possum",
    "potoo",
    "potoo bird",
    "potoroo",
    "prairie dog",
    "prawn",
    "procoptodon",
    "pronghorn",
    "pteranodon",
    "pterodactyl",
    "pudelpointer",
    "puertasaurus",
    "puff adder",
    "pufferfish",
    "puffin",
    "pug",
    "pugapoo",
    "puggle",
    "pugshire",
    "puli",
    "puma",
    "pumi",
    "purple finch",
    "purussaurus",
    "puss moth",
    "pygmy python",
    "pygmy shark",
    "pygora goat",
    "pyjama shark",
    "pyrador",
    "pyredoodle",
    "pyrosome",
    "python",
    "quagga",
    "quahog clam",
    "quail",
    "queen snake",
    "quetzal",
    "quetzal bird",
    "quokka",
    "quoll",
    "rabbit",
    "raccoon",
    "raccoon dog",
    "racer snake",
    "ragamuffin",
    "ragdoll",
    "raggle",
    "rainbow boa",
    "rat",
    "rat snake",
    "rat snakes",
    "rat terrier",
    "ratel",
    "ratfish",
    "rattlesnake",
    "red aphids",
    "red deer",
    "red finch",
    "red fox",
    "red kite",
    "red panda",
    "red squirrel",
    "red tail boa",
    "red wolf",
    "redfish",
    "redstart",
    "reef shark",
    "reindeer",
    "repenomamus",
    "rex rabbit",
    "rhea",
    "rhino beetle",
    "rhino viper",
    "rhinoceros",
    "ribbon eel",
    "ribbon snake",
    "right whale",
    "river otter",
    "river turtle",
    "roadrunner",
    "robber flies",
    "robin",
    "rock bass",
    "rock crab",
    "rock hyrax",
    "rock python",
    "rockfish",
    "rodents",
    "roe deer",
    "rooster",
    "root aphids",
    "rosy boa",
    "rotterman",
    "rottle",
    "rottsky",
    "rottweiler",
    "rove beetle",
    "rubber boa",
    "ruddy duck",
    "russian blue",
    "saanen goat",
    "sable",
    "sable ferret",
    "saiga",
    "sailfish",
    "salamander",
    "salmon",
    "salmon shark",
    "saluki",
    "sambar",
    "samoyed",
    "sand cat",
    "sand crab",
    "sand dollar",
    "sand lizard",
    "sand viper",
    "sandpiper",
    "sandworm",
    "saola",
    "sapsali",
    "sarcosuchus",
    "sardines",
    "sarkastodon",
    "sarplaninac",
    "sarus crane",
    "sauropoda",
    "savanna goat",
    "savu python",
    "sawfish",
    "scallops",
    "schapendoes",
    "schipperke",
    "schneagle",
    "schnoodle",
    "scorpion",
    "scorpionfish",
    "scrotum frog",
    "sculpin",
    "scutosaurus",
    "sea anemone",
    "sea bass",
    "sea cucumber",
    "sea dragon",
    "sea eagle",
    "sea lion",
    "sea otter",
    "sea roach",
    "sea slug",
    "sea snake",
    "sea spider",
    "sea squirt",
    "sea trout",
    "sea turtle",
    "sea urchin",
    "seagull",
    "seahorse",
    "seal",
    "sei whale",
    "seriema bird",
    "serval",
    "seymouria",
    "shark",
    "shastasaurus",
    "sheep",
    "sheepadoodle",
    "shepadoodle",
    "shepkita",
    "shepweiler",
    "shiba inu",
    "shichi",
    "shih poo",
    "shih tzu",
    "shikoku",
    "shiranian",
    "shollie",
    "shrew",
    "shrimp",
    "siamese",
    "siberian",
    "siberpoo",
    "sidewinder",
    "sifaka",
    "sika deer",
    "silky shark",
    "simbakubwa",
    "sivatherium",
    "skate fish",
    "skink lizard",
    "skua",
    "skunk",
    "skye terrier",
    "sloth",
    "slovak cuvac",
    "slow loris",
    "slow worm",
    "slug",
    "smilosuchus",
    "smooth snake",
    "snail",
    "snailfish",
    "snake",
    "snook fish",
    "snorkie",
    "snow bunting",
    "snow crab",
    "snow goose",
    "snow leopard",
    "snowshoe",
    "snowy owl",
    "somali",
    "song sparrow",
    "song thrush",
    "sow bug",
    "spalax",
    "spanador",
    "spanish goat",
    "sparrow",
    "sparrowhawk",
    "sperm whale",
    "sphynx",
    "spider",
    "spider wasp",
    "spinosaurus",
    "spixs macaw",
    "sponge",
    "spongy moth",
    "spoonbill",
    "spotted bass",
    "spotted gar",
    "springador",
    "springbok",
    "squash bee",
    "squid",
    "squirrel",
    "squirrelfish",
    "stabyhoun",
    "stag beetle",
    "starfish",
    "starling",
    "stick insect",
    "stingray",
    "stoat",
    "stone crab",
    "stonechat",
    "stonefish",
    "stork",
    "striped bass",
    "stromatolite",
    "stupendemys",
    "sturgeon",
    "suchomimus",
    "suckerfish",
    "sugar glider",
    "sun bear",
    "supersaurus",
    "superworm",
    "surgeonfish",
    "swai fish",
    "swallow",
    "swan",
    "swordfish",
    "taco terrier",
    "taimen fish",
    "taipan",
    "takin",
    "tamarin",
    "tamaskan",
    "tang",
    "tapir",
    "tarantula",
    "tarbosaurus",
    "tarpon",
    "tarsier",
    "tawny owl",
    "tegu",
    "tenrec",
    "termite",
    "tern",
    "terrier",
    "terror bird",
    "tetra",
    "texas heeler",
    "theropod",
    "thorny devil",
    "thrush",
    "thylacoleo",
    "tibetan fox",
    "tick",
    "tiffany",
    "tiger",
    "tiger beetle",
    "tiger moth",
    "tiger shark",
    "tiger snake",
    "tiger trout",
    "tiktaalik",
    "timor python",
    "titan beetle",
    "titanoboa",
    "titanosaur",
    "toad",
    "toadfish",
    "tokay gecko",
    "torkie",
    "tornjak",
    "tortoise",
    "tosa",
    "toucan",
    "towhee",
    "toxodon",
    "toy poodle",
    "tree cricket",
    "tree frog",
    "tree snake",
    "tree swallow",
    "tree viper",
    "treecreeper",
    "treehopper",
    "triggerfish",
    "troodon",
    "tropicbird",
    "trout",
    "tsetse fly",
    "tuatara",
    "tuna",
    "tundra swan",
    "turaco",
    "turkey",
    "turnspit",
    "turtle",
    "turtle frog",
    "turtles",
    "tusoteuthis",
    "tussock moth",
    "twig snake",
    "tylosaurus",
    "uakari",
    "uaru cichlid",
    "uguisu",
    "uintatherium",
    "umbrellabird",
    "unau",
    "ural owl",
    "urial",
    "uromastyx",
    "urutu snake",
    "utonagan",
    "vampire bat",
    "vampire crab",
    "vaquita",
    "veery",
    "vegavis",
    "velociraptor",
    "vicuña",
    "vine snake",
    "vinegaroon",
    "viper",
    "viper boa",
    "viper shark",
    "viperfish",
    "vizsla",
    "vole",
    "vulture",
    "wahoo fish",
    "waimanu",
    "wallaby",
    "walleye fish",
    "walrus",
    "warbler",
    "warthog",
    "wasp",
    "water beetle",
    "water bug",
    "water dragon",
    "water vole",
    "waterbuck",
    "wax moth",
    "weasel",
    "weaver bird",
    "weddell seal",
    "weimaraner",
    "weimardoodle",
    "wels catfish",
    "welsh corgi",
    "westiepoo",
    "whale",
    "whale shark",
    "whimbrel",
    "whinchat",
    "whippet",
    "white bass",
    "white marlin",
    "white shark",
    "white tiger",
    "whiting",
    "whoodle",
    "wild boar",
    "wildebeest",
    "winter moth",
    "wiwaxia",
    "wolf",
    "wolf eel",
    "wolf snake",
    "wolf spider",
    "wolffish",
    "wolverine",
    "woma python",
    "wombat",
    "wood bison",
    "wood duck",
    "wood frog",
    "wood tick",
    "wood turtle",
    "woodlouse",
    "woodpecker",
    "woodrat",
    "worm",
    "worm snake",
    "wrasse",
    "wren",
    "wryneck",
    "wyoming toad",
    "x-ray tetra",
    "xeme",
    "xenacanthus",
    "xenoceratops",
    "xenoposeidon",
    "xenops",
    "xerus",
    "xiaosaurus",
    "xiaotingia",
    "xiphactinus",
    "yabby",
    "yak",
    "yarara",
    "yellow bass",
    "yellow cobra",
    "yellow perch",
    "yellow tang",
    "yellowhammer",
    "yellowjacket",
    "yellowthroat",
    "yeti crab",
    "yoranian",
    "yorkiepoo",
    "zebra",
    "zebra finch",
    "zebra pleco",
    "zebra shark",
    "zebra snake",
    "zebrafish",
    "zebu",
    "zokor",
    "zonkey",
    "zorse",
    "zuchon"
  }
  def nouns, do: @nouns
end
