defmodule SillySeahorse.Adverb do
  @moduledoc false
  @adverbs {
    "a bit",
    "a little",
    "a tad",
    "absolutely",
    "acceptably",
    "averagely",
    "awfully",
    "completely",
    "decently",
    "extremely",
    "fairly",
    "immensely",
    "incredibly",
    "kind of",
    "marginally",
    "medium",
    "moderately",
    "modestly",
    "pretty",
    "quite",
    "rather",
    "really",
    "reasonably",
    "relatively",
    "slightly",
    "somewhat",
    "sort of",
    "super",
    "terribly",
    "tolerably",
    "totally",
    "utterly",
    "very",
    "overly",
    "extra",
    "vastly",
    "wildly",
    "faintly",
    "scarcely",
    "hardly",
    "barely"
  }

  def adverbs(), do: @adverbs
end
